<?php

namespace SchoolPalm\ModuleSDK\Resolvers;

use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use SchoolPalm\ModuleBridge\Contracts\ResolverContract;

/**
 * Class ModuleResolver
 *
 * Responsible for resolving module paths, main classes, actions, and Vue/Inertia components
 * based on the module registry. It provides helpers for vendors developing modules
 * in SchoolPalm SDK.
 *
 * Module structure conventions:
 * - Vendor: from module registry
 * - Level: extracted from namespace (e.g., Common, Secondary)
 * - Role: from registry, default 'Admin'
 * - Module: name of the module
 *
 * Component path structure: vendor/level/role/module/action
 *
 * @package SchoolPalm\ModuleSDK\Resolvers
 */
class ModuleResolver implements ResolverContract
{
    /**
     * Module registry
     *
     * @var array
     */
    protected array $registry;

    /**
     * ModuleResolver constructor.
     *
     * @param array $registry Module registry array generated by SDK
     */
    public function __construct(array $registry)
    {
        $this->registry = $registry;
    }

    /* -------------------------------------------------------------
     |  Registry
     | -------------------------------------------------------------
     */

    /**
     * Get module data by name (or key)
     *
     * @param string $module Module name
     * @return array|null
     */
    public function getModuleData(string $module): ?array
    {
        $module = Str::lower($module);

        foreach ($this->registry as $entry) {
            if (Str::endsWith($entry['module_key'], ".$module")) {
                return $entry;
            }
        }

        return null;
    }

    /* -------------------------------------------------------------
     |  Main Class
     | -------------------------------------------------------------
     */

    /**
     * Resolve the main class of a module
     *
     * @param string $module Module name
     * @return string Fully-qualified class name
     */
    public function resolveModuleMainClass(string $module): string
    {
        $data = $this->requireModule($module);

        $class = $data['namespace'] . '\\Main';

        if (!class_exists($class)) {
            abort(404, "Main class not found for module: {$module}");
        }

        return $class;
    }

    /* -------------------------------------------------------------
     |  Actions
     | -------------------------------------------------------------
     */

    /**
     * Get the filesystem path of module actions
     *
     * @param string $module Module name
     * @return string|null
     */
    public function resolveActionPath(string $module): ?string
    {
        $data = $this->getModuleData($module);
        return $data ? rtrim($data['path'], '/') . '/Actions' : null;
    }

    /**
     * Get the namespace for module actions
     *
     * @param string $module Module name
     * @return string|null
     */
    public function resolveActionNamespace(string $module): ?string
    {
        $data = $this->getModuleData($module);
        return $data ? $data['namespace'] . '\\Actions' : null;
    }

    /* -------------------------------------------------------------
     |  Vue / Inertia Components
     | -------------------------------------------------------------
     */

    /**
     * Resolve the Inertia/Vue component path for a module action
     *
     * @param string $module Module name
     * @param string $action Action name (default: 'Index')
     * @return string Component path
     */
    public function resolveComponent(string $module, string $action = 'Index'): string
    {
        $data = $this->requireModule($module);
        $action = Str::studly($action);

        $role = $data['role'] ?? 'Admin';
        $level = $this->extractLevelFromNamespace($data['namespace']);

        $path = $this->buildComponentPath($data['vendor'], $level, $role, $module, $action);

        if (!File::exists(resource_path("js/Pages/{$path}.vue"))) {
            abort(404, "Vue component not found for module: {$module}");
        }

        return $path;
    }

    /**
     * Get base component path for a module (vendor/level/role/module)
     *
     * @param string $module
     * @return string
     */
    public function resolveModuleComponentBase(string $module): string
    {
        $data = $this->requireModule($module);
        $level = $this->extractLevelFromNamespace($data['namespace']);
        $role = $data['role'] ?? 'Admin';
        return "Modules/{$data['vendor']}/{$level}/{$role}/{$module}";
    }

    /**
     * Build full Vue/Inertia component path
     *
     * @param string $vendor
     * @param string $level
     * @param string $role
     * @param string $module
     * @param string $action
     * @return string
     */
    protected function buildComponentPath(string $vendor, string $level, string $role, string $module, string $action): string
    {
        return "Modules/{$vendor}/{$level}/{$role}/{$module}/{$action}";
    }

    /**
     * Extract the academic level from the module namespace
     *
     * @param string $namespace
     * @return string
     */
    protected function extractLevelFromNamespace(string $namespace): string
    {
        $parts = explode('\\', $namespace);
        return $parts[1] ?? 'Common';
    }

    /* -------------------------------------------------------------
     |  Dashboard (SDK default)
     | -------------------------------------------------------------
     */

    /**
     * Get default dashboard component path
     *
     * @return string
     */
    public  function resolveDashboard(): string
    {
        return 'Dashboard/Index';
    }

    /* -------------------------------------------------------------
     |  Utilities
     | -------------------------------------------------------------
     */

    /**
     * Require a module from the registry
     *
     * @param string $module
     * @return array
     */
    protected function requireModule(string $module): array
    {
        $data = $this->getModuleData($module);

        if (!$data) {
            abort(404, "Module {$module} not found in registry.");
        }

        return $data;
    }
}
